populate_sdk_base.bbclass: add handling package exclusions to do_populate_sdk
Issue: LIN9-1460

Reproduce steps:
echo "PACKAGE_EXCLUDE = \"dpkg-start-stop\"" >> conf/local.conf
bitbake wrlinux-image-glibc-std -c populate_sdk

Error log:
[snip]
Computing transaction...error: Can't install
dpkg-start-stop-1.18.7-r0@core2_64: it's locked
ERROR: wrlinux-image-glibc-std-1.0-r5 do_populate_sdk: Function failed:
do_populate_sdk

Add handling package exclusions to do_populate_sdk which is same in
do_rootfs

(LOCAL REV: NOT UPSTREAM) -- will send to oe-core on 20161114

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>
Signed-off-by: Robert Yang <liezhi.yang@windriver.com>