oe/path.py: fix for "Argument list too long"
Issue: LIN9-1648

This patch came from Robert Yang, it can fix this issue, we can check it here:
	http://cgit.openembedded.org/openembedded-core-contrib/commit/?h=rbt/long&id=9eea4dacad1fe19b7d7dd43f542a1e01bd2a56d4

Fixed when len(TMPDIR) = 410:
$ bitbake core-image-sato-sdk
[snip]
Subprocess output:
/bin/sh: /bin/cp: Argument list too long

ERROR: core-image-sato-sdk-1.0-r0 do_rootfs: Function failed: do_rootfs
[snip]

This is because "copyhardlinktree(src, dst)" does "cp -afl src/* dst",
while src/* is expanded to "src/file1 src/file2, src/file3..." which
causes the "Argument list too long", use ./* as src and change cwd in
subprocess.check_output() to fix the problem.

(LOCAL REV: NOT UPSTREAM) -- pick up from openembedded-core-contrib

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Dengke Du <dengke.du@windriver.com>