openssl-1.1.1m: fix ptest failure
Issue: LIN1019-7821

This fixes an evp_extra_test ptest failure introduced by the upgrade to
openssl-1.1.1m:
"""
evp_extra_test
<snip>
not ok 19 - test_signatures_with_engine
ERROR: (ptr) 'e = ENGINE_by_id(engine_id) != NULL' failed @ ../openssl-1.1.1m/test/evp_extra_test.c:1890
0x0
not ok 20 - test_cipher_with_engine
<snip>
"""

This ptest change is already present in Yocto master since oe-core
commit 5cd40648b0ba ("openssl: upgrade to 3.0.1").

(LOCAL REV: NOT UPSTREAM) -- wrspecific

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>