pulseaudio: define -mfloat-abi=softfp for CC on armv5
Issue: LINCD-3903

After pulseaudio upgrades from 13.0 to 14.0, it also switches from autotools
to meson and there's no option for disabling Neon optimizations with meson.
And the build system adds -mfpu=neon at the end of the compiler command line
which overrids any earlier -mfpu options and result below build failure:

| /prj/tmp-glibc/work/armv5e-wrs-linux-gnueabi/pulseaudio/14.0-r0/recipe-sysroot-native/usr/lib/arm-wrs-linux-gnueabi/gcc/arm-wrs-linux-gnueabi/10.2.0/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
|  31 | #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softfp or -mfloat-abi=hard"
      |  ^~~~~
| ../pulseaudio-14.0/src/pulsecore/mix_neon.c: In function 'pa_mix_ch2_s16ne_neon':
| ../pulseaudio-14.0/src/pulsecore/mix_neon.c:38:9: error: unknown type name 'int32x4_t'; did you mean 'int32_t'?
|   38 |         int32x4_t sum0, sum1;

Define -mfloat-abi=softfp for CC on armv5 to fix the above issue.

(LOCAL REV: NOT UPSTREAM) -- Rejected by upstream and it is just a
                             wordaround locally as oe-core prefers
                             to wait pulseaudio upstream to support
                             a option to disable the neon or improve
                             meson build system to detect neon support

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>