populate_sdk_base: only depend on nativesdk-glibc-locale when SDK_OS is not mingw32
Issue: LIN9-7305

When we add the nativesdk-glibc-locale dependence for libc-glibc, if the SDK_OS
is mingw32, it will broken the building with the following error:
>NOTE: Resolving any missing task queue dependencies
>ERROR: Nothing RPROVIDES 'nativesdk-glibc' (but virtual:nativesdk:layers/oe-core/meta/recipes-core/glibc/glibc-locale_2.24.bb
>RDEPENDS on or otherwise requires it)
>ERROR: nativesdk-glibc was skipped: PREFERRED_PROVIDER_virtual/nativesdk-libc set to nativesdk-mingw-w64-runtime, not nativesdk-glibc
>NOTE: Runtime target 'nativesdk-glibc' is unbuildable, removing...
>Missing or unbuildable dependency chain was: ['nativesdk-glibc']
>ERROR: Required build target 'meta-toolchain' has no buildable providers.
>Missing or unbuildable dependency chain was: ['meta-toolchain', 'nativesdk-glibc-locale', 'nativesdk-glibc']

(LOCAL REV: NOT UPSTREAM) -- Send to oe-core later

Signed-off-by: Zhixiong Chi <zhixiong.chi@windriver.com>