grub-efi.bbclass: remove MLPREFIX from grub-efi
Issue: LIN10-3454

Fixed:
MACHINE = "intel-x86-64"
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "x86"
IMAGE_FSTYPES=" tar.bz2 wic wic.bmap live"

$ bitbake lib32-core-image-minimal
Exception: FileExistsError: [Errno 17] File exists:
'path/to/sysroots-components/corei7-32/lib32-gcc-runtime/usr/share/gcc-7.3.0/python/libstdcxx/__init__.py' ->
'path/to/work/intel_x86_64-wrsmllib32-linux/lib32-wrlinux-image-glibc-small/1.0-r1/lib32-recipe-sysroot/usr/share/gcc-7.3.0/python/libstdcxx/__init__.py'

ERROR: lib32-wrlinux-image-glibc-small-1.0-r1 do_bootimg: Function failed: extend_recipe_sysroot
ERROR: Logfile of failure stored in: path/to/work/intel_x86_64-wrsmllib32-linux/lib32-wrlinux-image-glibc-small/1.0-r1/temp/log.do_bootimg.99618
code '1'

This was because:
lib32-grub-efi -> lib32-gcc-runtime
syslinux -> gcc-runtime

It doesn't make any sense to build a multilib bootloader (grub-efi), so use 64
bit for it as we did for syslinux, and here is the reason why we built 64bit
syslinux:

If we built lib32-syslinux when do_bootimg, there would be errors:
$ bitbake lib32-core-image-minimal
ERROR: lib32-core-image-minimal-1.0-r0 do_bootimg: The file
/include/printf.h is installed by both glibc and lib32-glibc, aborting

This was because:
lib32-syslinux -> lib32-glibc
virtual/kernel -> glibc

So we built 64bitbake for it.

(LOCAL REV: NOT UPSTREAM) -- Sent to oe-core on 20180314

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>