webkitgtk/epiphany: add opengl to REQUIRED_DISTRO_FEATURES
They can't be built without opengl in DISTRO_FEATURES.
[snip]
|webkitgtk-2.20.3/Source/WebCore/platform/graphics/OpenGLShims.h:23:10:
fatal error: GL/gl.h: No such file or directory
[snip]

Some sort of GL is needed yes. We indicate that with opengl loosely in OE

The epiphany depends on webkitgtk, add opengl to REQUIRED_DISTRO_FEATURES also.

Issue: LIN1018-2518

(LOCAL REV: NOT UPSTREAM) -- sent to oe-core on 20181010

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>